package com.hill.customview.glidedemo;

import android.app.Activity;
import android.content.Context;
import android.os.Bundle;
import android.widget.ListView;

import com.hill.customview.R;

import java.util.ArrayList;

/**
 * Created by hill on 17/3/28.
 */

public class glideDemoActivity extends Activity {
    private String TAG = "hill/glideView";

    private Context mContext;

    //设置图片请求的基础地址
    private static final String BASE_URL = "http://img1.3lian.com/img2011/w1/106/85/";
    private ArrayList<Product> dishList = new ArrayList<Product>();
    private ListView mProductListView;
    private ProductListViewAdapter mAdapter;

    @Override
    public void onCreate(Bundle onSavedInstance) {
        super.onCreate(onSavedInstance);
        setContentView(R.layout.layout_glide);

        fillData();
        initView();
    }

    private void initView() {
        mProductListView = (ListView) findViewById(R.id.listview);
        mAdapter = new ProductListViewAdapter(dishList, this);
        mProductListView.setAdapter(mAdapter);
    }

    private void fillData() {
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));



        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
        dishList.add(new Product(BASE_URL + "42.jpg", "水煮鱼片", "38.00"));
        dishList.add(new Product(BASE_URL + "34.jpg", "小炒肉", "18.00"));
        dishList.add(new Product(BASE_URL + "37.jpg", "清炒时蔬", "15.00"));
        dishList.add(new Product(BASE_URL + "11.jpg", "金牌烤鸭", "36.00"));
        dishList.add(new Product(BASE_URL + "12.jpg", "粉丝肉煲", "20.00"));
    }
}
